### For reference, see `/opt/open5gs/etc/orig/open5gs/`
amf:
  sbi:
    - addr: 172.16.2.253
      port: 7777
  ngap:
    - addr: 172.16.2.253
      port: 38412
  guami:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      tac: 1
  plmn_support:
    - plmn_id:
        mcc: "999"
        mnc: "70"
      s_nssai:
        - sst: 1
          sd: "0x01b207"
        - sst: 1
          sd: "0x111111"
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Gradiant5G
    short: G5G
  amf_name: amf

nrf:
  sbi:
    - addr: 172.22.0.5
      port: 7777

parameter:
max:
pool:
time:
