### For reference, see `/opt/open5gs/etc/orig/open5gs/`
nssf:
  sbi:
    - dev: eth0
      port: 7777
  nsi:
    - addr: 172.22.0.5
      port: 7777
      s_nssai:
        sst: 1
    - addr: 172.22.0.5
      port: 7777
      s_nssai:
        sst: 1
        sd: "0x111111"
    - addr: 172.22.0.5
      port: 7777
      s_nssai:
        sst: 1
        sd: "0x01b207"
nrf:
  sbi:
    - addr: 172.22.0.5
      port: 7777

parameter:
max:
pool:
time: