### For reference, see `/opt/open5gs/etc/orig/open5gs/`
smf:
  sbi:
    - dev: eth0
      port: 7777
  gtpc:
  gtpu:
  pfcp: null
  subnet:
    - addr: 10.45.0.1/16
      dnn: internet
    #- addr: cafe::1/64

  dns:
    - 8.8.8.8
    - 8.8.4.4
    #- 2001:4860:4860::8888
    #- 2001:4860:4860::8844
  mtu: 1500
  #freeDiameter: smf.conf

nrf:
  sbi:
    - addr: 172.22.0.5
      port: 7777
upf:
  pfcp:
    - addr: 172.16.2.253
      dnn: internet

parameter:
max:
pool:
time:
